# Generated by Django 5.1.5 on 2025-02-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_atribute_attributevalue_productattribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atribute',
            new_name='Attribute',
        ),
    ]
