# Generated by Django 5.1.5 on 2025-02-05 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_product_likes_alter_productattribute_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='like_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
