# Generated by Django 5.1.5 on 2025-02-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_product_rating_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ecommerce.product'),
        ),
    ]
